Vagrant.configure("2") do |config|
  # Configuration for the first VM
  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.box = "ubuntu/bionic64" # You can change this box to another Ubuntu 20.04 box if desired
    ubuntu1.vm.hostname = "ubuntu1"
    ubuntu1.vm.network "private_network", type: "dhcp" # Creates a private network interface
    ubuntu1.vm.provider "virtualbox" do |vb|
      vb.memory = 1024 # Adjust the memory size as per your requirements
      vb.cpus = 1 # Adjust the number of CPUs as per your requirements
    end
  end

  # Configuration for the second VM
  config.vm.define "ubuntu2" do |ubuntu2|
    ubuntu2.vm.box = "ubuntu/bionic64" # You can change this box to another Ubuntu 20.04 box if desired
    ubuntu2.vm.hostname = "ubuntu2"
    ubuntu2.vm.network "private_network", type: "dhcp" # Creates a private network interface
    ubuntu2.vm.provider "virtualbox" do |vb|
      vb.memory = 1024 # Adjust the memory size as per your requirements
      vb.cpus = 1 # Adjust the number of CPUs as per your requirements
    end
  end
end

